module.exports.data = {
   "data":3,
   "left":{
      "data":2,
      "left":{
         "data":1,
         "left":null,
         "right":null
      },
      "right":null
   },
   "right":{
      "data":5,
      "left":{
         "data":4,
         "left":null,
         "right":null
      },
      "right":{
         "data":6,
         "left":null,
         "right":{
            "data":7,
            "left":null,
            "right":null
         }
      }
   }
};
